apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    namespace "com.tencent.dpt"

    defaultConfig {
        applicationId "com.tencent.dpt"
        archivesBaseName = "$applicationId"

        minSdk 33
    }

    externalNativeBuild {
        cmake {
            version "3.22.1"
            path file('src/main/jni/CMakeLists.txt')
        }
    }

    dependencies {
        implementation 'com.android.support:support-v4:24.0.0'
    }
}
