apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    namespace "com.tencent.dpt"

    defaultConfig {
        applicationId "com.tencent.dpt"
        archivesBaseName = "$applicationId"

        minSdk 33
    }

    externalNativeBuild {
        cmake {
            version "3.22.1"
            path file('src/main/jni/CMakeLists.txt')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    dependencies {
        implementation 'com.android.support:support-v4:28.0.0'
        implementation 'androidx.heifwriter:heifwriter:1.1.0-rc02'
        implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
    }
}
